language: generic
sudo: required
services: docker
addons:
  apt:
    update: true
    packages:
    - qemu-user-static
    - binfmt-support

env:
  matrix:
  - TARGET=ux64 CHROOT=xenial-amd64 ARCH=amd64
  - TARGET=u710 CHROOT=xenial-arm64 ARCH=arm64
  - TARGET=u530 CHROOT=xenial-armhf ARCH=armhf

install:
- update-binfmts --display
- docker system info
- sudo rm /dev/shm
- sudo mkdir /dev/shm
- sudo mount --bind /run/shm /dev/shm
- docker pull webispy/artik_devenv_$TARGET

script:
- docker run -it --name builder --privileged -v /var/lib/schroot -v $PWD:/home/work/src
  -w /home/work/src webispy/artik_devenv_$TARGET bash -c "mkdir /home/work/result
  && sbuild --chroot $CHROOT --arch $ARCH --dpkg-source-opts=\"-I.git*\" && cp /home/work/*.deb
  /home/work/result/"

before_deploy:
- docker cp builder:/home/work/result /tmp/
- ls -l /tmp/result

deploy:
  provider: releases
  api_key:
    secure: TSVD2NcevnI4SiRhj5rcswEUhz3TADtBfqHzzMmgVwvlhzvSPUTEdHqcxeQszXURbFcJAz9bxt1AGDvWcsisCyhxMNRfIvZxmZBa5PCyP+5twLPvp8kKu7fpUH60wEUyjlhSbPQsN6MiueVhA30Tjuu4Cl36qkZp2UEGrpC+HmCqLG43k+cDbhobUh3D8494voSMbaXUAz42IJuY2GlBPCBP8D6bXcdAupPiJ1QFPJkOIS0yMhybmqTsbNaqsG7sy9xFDvM959wRbjVznQibDH76nwfmRAGQa1H//qqO3KVNz1ML4X2SygG6VKx62shEzptrEowU/bSMTaPu/Adexex/PW+w8qYAJuNYlsRUoDRxTD/RTPHAsH+LlXStJ207OCmEeXLzfNzDd3ZnsJI5RWEDJ+AUOhaaidDkj6y0gKd99YaE0FHB62yXN7XCtwcwYl5ILbxHVhaTfR/4vniWeADr2i3j6focNEyqToaKUR2TArNPGS2EytmEufs0gInOHm+DPQ/5jVQyGyDZCMfAo2tlvq8JGYf6n25IkXUjGiJxgLLqHj+AdAjr54tfCJTCJAZqKwXvWrIerPW9VAGngsLo47pqwOjM0kVyM9Dr7KVpvr1AOBq0BdWc32GmX64wC9Stg01au2YmJ/jbdtbfJ1/96R8Z+9r5qNAgjnptu34=
  file_glob: true
  file: /tmp/result/*
  skip_cleanup: true
  on:
    repo: webispy/grpc
    branch: v1.19.x
    tags: true
